name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0/3 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make lockfile
      run: cargo generate-lockfile
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: setup secrets
      run: mkdir secret && echo "${{secrets.GOOGLE_CALENDER_INFO}}" | base64 -d > secret/google_calender_info.json && echo "${{secrets.GOOGLE_CREDENTIAL}}" | base64 -d > secret/google_credential.json
    - name: check size
      run: ls -al secret/
    - name: Run
      run: ./run.sh
